name: CI

on: push

jobs:
  test:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macOS
            destination: platform=macOS
          - platform: iOS
            destination: platform=iOS Simulator,name=iPhone 17
          - platform: tvOS
            destination: platform=tvOS Simulator,name=Apple TV
          - platform: watchOS
            destination: platform=watchOS Simulator,name=Apple Watch Series 11 (46mm)
    name: test-${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: xcodebuild test -scheme Qualtive -destination '${{ matrix.destination }}'
